{% set name = "testPkg" %}
{% set version = "1.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../
  #folder: my-destination/folder
  #url: https://sourceforge.net/projects/ngopt/files/a5_miseq_linux_{{ version }}.tar.gz
  #sha256: 76a2798d617d45f4539e73ef2df5f899503ac4a54c3a406faf37db6282127fe9

build:
  noarch: generic
  number: 1

requirements:
  build:
    - perl
    - perl-app-cpanminus
    - r
    - pkg-config
    - wise2
    - perl-bioperl
    - perl-bioperl-core
    - perl-bioperl-run
    - blast
    - blast-legacy
    - hmmer
    - clustalw
    - mafft
    - muscle
  run:
    - perl
    - perl-app-cpanminus
    - r
    - pkg-config
    - wise2
    - perl-bioperl
    - perl-bioperl-core
    - perl-bioperl-run
    - blast
    - blast-legacy
    - hmmer
    - clustalw
    - mafft
    - muscle

test:
  commands:
    - testPkg.pl 2>&1

about:
  home: 'https://sourceforge.net/projects/ngop'
  license: GPLv3
  summary: "A5-miseq is a pipeline for assembling DNA sequence data generated on the Illumina sequencing platform. This README will take you through the steps necessary for running _A5-miseq_"
